# Generated by Django 4.2.28 on 2026-02-20 00:34

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('overall_score', models.FloatField(blank=True, null=True)),
                ('overall_grade', models.CharField(blank=True, default='', max_length=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('repo_url', models.URLField(blank=True, default='')),
                ('frontend_url', models.URLField(blank=True, default='', help_text='Live frontend URL for real-time probing')),
                ('backend_url', models.URLField(blank=True, default='', help_text='Live backend/API URL for real-time probing')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MetricSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('dimension', models.CharField(choices=[('frontend', 'Frontend'), ('backend', 'Backend'), ('database', 'Database'), ('structure', 'Structure'), ('api', 'API'), ('integration', 'Integration'), ('security', 'Security')], max_length=20)),
                ('metric_name', models.CharField(help_text='e.g. Frontend_load_time, Backend_proc_time, Database_query_time, etc.', max_length=100)),
                ('raw_value', models.FloatField(help_text='Raw measurement value')),
                ('unit', models.CharField(default='ms', help_text='e.g. ms, %, score', max_length=30)),
                ('weight', models.FloatField(default=1.0, help_text='Weight assigned by the AI engine')),
                ('normalised_score', models.FloatField(blank=True, help_text='Score normalised to 0-100', null=True)),
                ('grade', models.CharField(blank=True, default='', max_length=2)),
                ('threshold_good', models.FloatField(blank=True, null=True)),
                ('threshold_warning', models.FloatField(blank=True, null=True)),
                ('threshold_critical', models.FloatField(blank=True, null=True)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('measured_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('analysis_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='analyser.analysisrun')),
            ],
            options={
                'ordering': ['dimension'],
            },
        ),
        migrations.AddField(
            model_name='analysisrun',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_runs', to='analyser.project'),
        ),
        migrations.CreateModel(
            name='HistoricalTrend',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('dimension', models.CharField(max_length=20)),
                ('metric_name', models.CharField(max_length=100)),
                ('value', models.FloatField()),
                ('score', models.FloatField(blank=True, null=True)),
                ('recorded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trends', to='analyser.project')),
            ],
            options={
                'ordering': ['-recorded_at'],
                'indexes': [models.Index(fields=['project', 'dimension', 'recorded_at'], name='analyser_hi_project_fbd242_idx')],
            },
        ),
    ]
