# Generated by Django 4.2.28 on 2026-02-22 11:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('analyser', '0005_payment_invoice'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='invoice',
            new_name='analyser_in_user_id_3a5e10_idx',
            old_name='analyser_in_user_id_issued_idx',
        ),
        migrations.RenameIndex(
            model_name='invoice',
            new_name='analyser_in_status_2b92f3_idx',
            old_name='analyser_in_status_idx',
        ),
        migrations.RenameIndex(
            model_name='payment',
            new_name='analyser_pa_user_id_47a86e_idx',
            old_name='analyser_pa_user_id_created_idx',
        ),
        migrations.RenameIndex(
            model_name='payment',
            new_name='analyser_pa_status_1fc769_idx',
            old_name='analyser_pa_status_idx',
        ),
        migrations.RenameIndex(
            model_name='project',
            new_name='analyser_pr_user_id_f2743a_idx',
            old_name='analyser_pr_user_id_created_idx',
        ),
        # migrations.AlterField(
        #     model_name='project',
        #     name='user',
        #     field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL),
        # ),
    ]
