# Generated by Django 4.2.28 on 2026-02-22 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyser', '0006_rename_analyser_in_user_id_issued_idx_analyser_in_user_id_3a5e10_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='razorpay_payment_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='razorpay_payment_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='razorpay_signature',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='razorpay_subscription_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
    ]
