# Generated by Django 4.2.28 on 2026-03-01 16:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def backfill_project_user(apps, schema_editor):
    Project = apps.get_model('analyser', 'Project')
    User = apps.get_model('auth', 'User')

    if not Project.objects.filter(user__isnull=True).exists():
        return

    user = User.objects.order_by('id').first()
    if user is None:
        user = User.objects.create(
            username='legacy_owner',
            email='legacy_owner@local.invalid',
            is_active=False,
        )

    Project.objects.filter(user__isnull=True).update(user_id=user.id)


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('analyser', '0007_alter_invoice_razorpay_payment_id_and_more'),
    ]

    operations = [
        migrations.RunPython(backfill_project_user, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='project',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL),
        ),
    ]
