# Generated by Django 4.2.28 on 2026-03-03 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyser', '0008_alter_project_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisrun',
            name='embeddings_generated',
            field=models.BooleanField(default=False, help_text='Whether RAG embeddings have been generated for this run'),
        ),
        migrations.AddField(
            model_name='analysisrun',
            name='suggested_improvements',
            field=models.JSONField(blank=True, default=list, help_text='Auto-generated suggestions for improvement based on weak dimensions'),
        ),
    ]
