# Generated by Django 4.2.28 on 2026-03-05 05:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('analyser', '0009_analysisrun_embeddings_generated_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question', models.CharField(max_length=500)),
                ('answer', models.TextField()),
                ('category', models.CharField(choices=[('general', 'General'), ('features', 'Features'), ('billing', 'Billing'), ('technical', 'Technical'), ('account', 'Account'), ('security', 'Security')], default='general', max_length=50)),
                ('order', models.IntegerField(default=0, help_text='Display order')),
                ('is_active', models.BooleanField(default=True)),
                ('views', models.IntegerField(default=0, help_text='Number of times this FAQ was viewed')),
                ('helpful_count', models.IntegerField(default=0, help_text='Times marked as helpful')),
                ('unhelpful_count', models.IntegerField(default=0, help_text='Times marked as unhelpful')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQs',
                'ordering': ['category', 'order'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, default='', help_text='User bio or about text')),
                ('avatar_url', models.URLField(blank=True, default='', help_text="URL to user's profile image")),
                ('phone_number', models.CharField(blank=True, default='', max_length=20)),
                ('company', models.CharField(blank=True, default='', max_length=255)),
                ('location', models.CharField(blank=True, default='', max_length=255)),
                ('website', models.URLField(blank=True, default='')),
                ('two_factor_enabled', models.BooleanField(default=False)),
                ('email_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='UserPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_notifications', models.BooleanField(default=True, help_text='Receive email notifications')),
                ('project_updates', models.BooleanField(default=True, help_text='Notify when projects are analyzed')),
                ('marketing_emails', models.BooleanField(default=False, help_text='Receive marketing emails')),
                ('weekly_digest', models.BooleanField(default=True, help_text='Receive weekly summary emails')),
                ('dark_theme', models.BooleanField(default=True, help_text='Enable dark theme')),
                ('notifications_popup', models.BooleanField(default=True, help_text='Show desktop notifications')),
                ('public_profile', models.BooleanField(default=False, help_text='Profile visible to public')),
                ('show_projects_publicly', models.BooleanField(default=False, help_text='Show projects on public profile')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(choices=[('technical', 'Technical Support'), ('billing', 'Billing Question'), ('feature', 'Feature Request'), ('bug', 'Bug Report'), ('general', 'General Inquiry')], max_length=20)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('new', 'New'), ('open', 'Open'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='new', max_length=20)),
                ('response', models.TextField(blank=True, default='', help_text='Admin response to the message')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='analyser_co_user_id_f48ed2_idx'), models.Index(fields=['status'], name='analyser_co_status_f67cf9_idx')],
            },
        ),
    ]
