# Generated by Django 4.2.28 on 2026-04-14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analyser", "0011_outboundwebhook"),
    ]

    operations = [
        migrations.AddField(
            model_name="plan",
            name="razorpay_plan_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Cached Razorpay plan ID to avoid creating duplicate remote plans",
                max_length=255,
                null=True,
                unique=True,
            ),
        ),
    ]
