# Generated by Django 4.2.28 on 2026-04-15 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyser', '0012_plan_razorpay_plan_id'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='analysisrun',
            index=models.Index(fields=['project', 'status', '-completed_at'], name='analyser_an_project_89cefa_idx'),
        ),
        migrations.AddIndex(
            model_name='metricsnapshot',
            index=models.Index(fields=['analysis_run', 'dimension'], name='analyser_me_analysi_e01108_idx'),
        ),
    ]
