# Generated by Django 4.2.28 on 2026-04-20 00:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analyser", "0013_analysisrun_analyser_an_project_89cefa_idx_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserFeedback",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("faced_error", models.BooleanField(default=False)),
                ("feature_understanding_problem", models.BooleanField(default=False)),
                ("environment", models.CharField(choices=[("phone", "Phone"), ("tablet", "Tablet"), ("pc", "PC")], max_length=10)),
                (
                    "software_quality_rating",
                    models.IntegerField(choices=[(1, "1 - Very Poor"), (2, "2 - Poor"), (3, "3 - Average"), (4, "4 - Good"), (5, "5 - Excellent")]),
                ),
                (
                    "software_performance_rating",
                    models.IntegerField(choices=[(1, "1 - Very Poor"), (2, "2 - Poor"), (3, "3 - Average"), (4, "4 - Good"), (5, "5 - Excellent")]),
                ),
                ("settings_working", models.BooleanField(default=True)),
                ("pricing_working", models.BooleanField(default=True)),
                ("analysis_understandable", models.BooleanField(default=True)),
                ("dashboard_working", models.BooleanField(default=True)),
                ("login_google_working", models.BooleanField(default=True)),
                ("comments", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="feedback_entries", to=settings.AUTH_USER_MODEL),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="userfeedback",
            index=models.Index(fields=["user", "-created_at"], name="analyser_us_user_id_65f27c_idx"),
        ),
    ]
