# Generated by Django 4.2.28 on 2026-05-01 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analyser', '0014_userfeedback'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='userfeedback',
            new_name='analyser_us_user_id_2d7832_idx',
            old_name='analyser_us_user_id_65f27c_idx',
        ),
    ]
