[pytest]
DJANGO_SETTINGS_MODULE = project_analyser.test_settings
python_files = tests.py test_*.py *_tests.py
python_classes = Test*
python_functions = test_*
addopts = --tb=short -q
filterwarnings =
    ignore::DeprecationWarning:graphql_jwt
    ignore::DeprecationWarning:graphql_jwt.utils
    ignore::DeprecationWarning:graphql_jwt.decorators
